FROM ruby:2.5

# Set default locale for the environment
ENV LC_ALL zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock jekyll-text-theme.gemspec ./

# RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "help"]